apiVersion: v1
kind: Secret
metadata:
  name: api-stress-s-{{.step}}-{{.Iteration}}-{{.Replica}}
  labels:
    app: kb-stress
    kb-step: "{{.step}}"
    kb-type: api
type: Opaque
data:
  padding: cGxhY2Vob2xkZXI=
